### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Bohicatv** [kaczy93/centredsharp#28]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at CentrED.UI.Windows.TilesWindow.DrawTileRow(Int32 index, TileInfo tileInfo)
   at CentrED.UI.Windows.TilesWindow.DrawTiles()
   at CentrED.UI.Windows.TilesWindow.InternalDraw()
   at CentrED.UI.Windows.Window.Draw()
   at CentrED.UI.UIManager.DrawUI()
   at CentrED.CentrEDGame.Draw(GameTime gameTime)
```

**Comment by Bohicatv** [comment]
type in armor on the static list and scroll all the way down which results in a crash every time for me.

**Comment by kaczy93** [comment]
Which CentrED# version is it? I fixed something very similar in 0.6.0.12.
Also which client version does it crash on, so I can reproduce it?

**Comment by Bohicatv** [comment]
Oh interesting. I missed the latest release. It seems to be fixed now and I like what you did with the list.
