### ISSUE TITLE
Consistent crash while working in available black space near map edges and using virtual layers

### ISSUE THREAD

**Issue by Bohicatv** [kaczy93/centredsharp#29]
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CentrED.Tools.BaseTool.OnMouseEnter(TileObject o)
   at CentrED.Map.MapManager.Update(GameTime gameTime, Boolean isActive, Boolean processMouse, Boolean processKeyboard)
   at CentrED.CentrEDGame.Update(GameTime gameTime)

**Comment by kaczy93** [comment]
Thanks for reporting this

Should be fixed in latest release 0.6.1.7

**Comment by Bohicatv** [comment]
fixed
